project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
    - Badgraph-1.qmd
    - Redesign(2)-1.qmd
    - Badgraph-2.qmd
    - fourth.qmd
    - codes.qmd
    - video-Explanation.qmd
    - references.qmd
    
format:
  html:
    theme: cosomo
    

