project:
  type: website
  output-dir: docs

website:
  title: "MidProject"
  navbar:
    left:
    - badgraph-1.qmd
    - redesign-1.qmd
    - badgraph-2.qmd
    - redesign(2)-1.qmd
    - codes.qmd
    - video-Explanation.qmd
    - references.qmd

    
format:
  html:
    theme: cosomo
    

