---
title: "Codes"
editor: visual
---

{{< video background-video="https://youtu.be/wo9vZccmqwc" >}}

```{r}
library(plotly)
data <- data.frame(
  month = factor(c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr"),
                 levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")),
  collapses = c(7, 6, 16, 17, 20, 28, 46, 57, 81, 109, 116, 124, 126, 73, 120, 55),
  deaths = c(4, 4, 8, 10, 7, 19, 33, 34, 43, 64, 77, 90, 86, 51, 83, 36)
)

# Create a plotly line plot
plot_ly(data, x = ~month, y = ~collapses, type = 'scatter', mode = 'lines', name = 'Collapses') %>%
  add_trace(y = ~deaths, name = 'Deaths') %>%
  layout(title = "Athlete Collapses and Deaths",
         xaxis = list(title = "Month"),
         yaxis = list(title = "Count", tickvals = c(0, 10, 20, 30,40,50,60,70,80,90,100,120)))
```

```{r}
library(plotly)

data <- data.frame(
  month = factor(c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", 
                   "Jan", "Feb", "Mar", "Apr"), 
                 levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")),
  collapses = c(7, 6, 16, 17, 20, 28, 46, 57, 81, 109, 116, 124, 126, 73, 120, 55),
  deaths = c(4, 4, 8, 10, 7, 19, 33, 34, 43, 64, 77, 90, 86, 51, 83, 36)
)

# Create a Plotly column bar chart
plot_ly(data, x = ~month, y = ~collapses, type = 'bar', name = 'Collapses', marker = list(color = 'skyblue', line = list(color = 'darkblue', width = 1))) %>%
  add_trace(x = ~month, y = ~deaths, name = 'Deaths', marker = list(color = 'coral', line = list(color = 'darkred', width = 1))) %>%
  layout(title = "Athlete Collapses and Deaths",
         xaxis = list(title = "Month"),
         yaxis = list(title = "Frequencies", tickvals = c(0, 10, 20, 30,40,50,60,70,80,90,100,120)), barmode = 'group')
```

```{r}
library(ggplot2)

co2_data <- data.frame(
  country = c("Brasil", "Argentina", "EEUU", "Italia", "Alemania", "Norurga"),
  emission = c(256, 330, 7000, 14100, 15700, 22300)
)

co2_data$country <- factor(co2_data$country, levels = co2_data$country)

gg <- ggplot(co2_data, aes(x = country, y = emission)) +
  geom_point(size = 3, color = "skyblue") +
  geom_text(aes(label = emission), vjust = -0.3, hjust = -0.2, color = "black") +  # Add labels
  labs(title = "Covid tests by Country",
       x = "Country",
       y = "covid tests in millions(m)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

gg
```

```{r}
library(leaflet)
library(rnaturalearth)


covid_data <- data.frame(
  country = c("Brazil", "Argentina", "United States of America", "Italy","Germany","Norway"),
  tests = c(258, 330, 7000, 14100,15700,22300)
)


world <- ne_countries(returnclass = "sf")


world_with_co2 <- merge(world, covid_data, by.x = "name", by.y = "country", all.x = TRUE)


leaflet_map <- leaflet(data = world_with_co2) %>%
  addTiles() %>%
  setView(lng = 0, lat = 0, zoom = 2) %>%  # Set initial view of the map
  addPolygons(
    fillColor = ~colorQuantile("Reds", tests)(tests),
    fillOpacity = 0.7,
    weight = 1,
    popup = ~paste(name, ": ", tests, " tests")
  ) %>%
  addLegend(
    position = "bottomright",
    pal = colorQuantile("Reds", covid_data$tests),
    values = covid_data$tests,
    title = "Covid test results"
  )


leaflet_map
```
